/*
Copyright 2019 The Cloud-Barista Authors.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package model is to handle object of CB-Tumblebug
package model

// SpiderImageReqInfoWrapper is a wrapper struct to create JSON body of 'Get image request'
type SpiderImageReqInfoWrapper struct {
	ConnectionName string
	ReqInfo        SpiderImageInfo
}

// SpiderImageInfo is a struct to create JSON body of 'Get image request'
type SpiderImageInfo struct {
	// Fields for request
	Name string

	// Fields for response
	IId          IID    // {NameId, SystemId}
	GuestOS      string // Windows7, Ubuntu etc.
	Status       string // available, unavailable
	KeyValueList []KeyValue
}

// TbImageReq is a struct to handle 'Register image' request toward CB-Tumblebug.
type TbImageReq struct {
	Name           string `json:"name" validate:"required"`
	ConnectionName string `json:"connectionName" validate:"required"`
	CspResourceId  string `json:"cspResourceId" validate:"required"`
	Description    string `json:"description"`
}

// TbImageInfo is a struct that represents TB image object.
type TbImageInfo struct {
	// Id is unique identifier for the object
	Id string `json:"id" example:"aws-ap-southeast-1"`
	// Uid is universally unique identifier for the object, used for labelSelector
	Uid string `json:"uid,omitempty" example:"wef12awefadf1221edcf"`
	// CspResourceName is name assigned to the CSP resource. This name is internally used to handle the resource.
	CspResourceName string `json:"cspResourceName,omitempty" example:"we12fawefadf1221edcf"`
	// CspResourceId is resource identifier managed by CSP
	CspResourceId string `json:"cspResourceId,omitempty" example:"csp-06eb41e14121c550a"`

	// Name is human-readable string to represent the object
	Name                 string     `json:"name" example:"aws-ap-southeast-1"`
	Namespace            string     `json:"namespace,omitempty" example:"default"` // required to save in RDB
	ConnectionName       string     `json:"connectionName,omitempty"`
	InfraType            string     `json:"infraType,omitempty"` // vm|k8s|kubernetes|container, etc.
	Description          string     `json:"description,omitempty"`
	CreationDate         string     `json:"creationDate,omitempty"`
	GuestOS              string     `json:"guestOS,omitempty"` // Windows7, Ubuntu etc.
	Status               string     `json:"status,omitempty"`  // available, unavailable
	KeyValueList         []KeyValue `json:"keyValueList,omitempty"`
	AssociatedObjectList []string   `json:"associatedObjectList,omitempty"`
	IsAutoGenerated      bool       `json:"isAutoGenerated,omitempty"`

	// SystemLabel is for describing the Resource in a keyword (any string can be used) for special System purpose
	SystemLabel string `json:"systemLabel,omitempty" example:"Managed by CB-Tumblebug" default:""`
}

// SpiderImageList is struct for Spider Image List
type SpiderImageList struct {
	Image []SpiderImageInfo `json:"image"`
}
