// Package docs registers the OpenAPI spec generated by `make swag`.
//
// swagger.yaml is the only generated artifact; embedding it here keeps
// echo-swagger (/tumblebug/api/*) serving exactly the spec that is published,
// so no separate docs.go/swagger.json copies have to be kept in sync.
package docs

import (
	_ "embed"
	"fmt"

	"github.com/swaggo/swag"
	"sigs.k8s.io/yaml"
)

//go:embed swagger.yaml
var swaggerYAML []byte

// swag serves the spec as JSON; echo-swagger converts it back for doc.yaml.
type spec struct {
	doc string
}

func (s *spec) ReadDoc() string {
	return s.doc
}

func init() {
	doc, err := yaml.YAMLToJSON(swaggerYAML)
	if err != nil {
		panic(fmt.Sprintf("docs: cannot parse embedded swagger.yaml: %v", err))
	}
	swag.Register(swag.Name, &spec{doc: string(doc)})
}
