#!/bin/bash
#### add Cloud-Barista user
useradd -s /bin/bash {{username}} -rm -G sudo;
chown -R {{username}}:{{username}} /home/{{username}};
echo "{{username}} ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers;
cp -r /root/.ssh /home/{{username}};
chown -R {{username}}:{{username}} /home/{{username}}/.ssh;