tumblebug:
  endpoint: http://localhost:1323
  auth:
    info: auth.json
  demo:
    nsId: kdemo-ns01
    mcisId: kdemo-mcis01
  api:
    mcisDynamic:
      reqBody: mcisDynamic.json

terrarium:
  endpoint: http://localhost:8888
  auth:
    info: auth.json
  demo:
    terrariumId: kdemo-rg01
