# https://docs.nhn.com/ko/Container/NKS/ko/user-guide/, 동적프로비저닝
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cinder-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: cinder.csi.openstack.org
volumeBindingMode: WaitForFirstConsumer
